# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69dcb8902124ce63d91130d6213aefd4f02481aa4952c1bad4d65a1bedf784f2d5e5da810b786c0a00a6593e8e5b2d1a5742165e828d7394e3e35403b00826cf

test:
  secret_key_base: d53a9567dcf7cbc86a9f280b42eb23c5c134e3d835394a446d3431e9107e224f794338396b7ea8241ac5c6f16d92cbf23ecc933b4d4f1f95c376b9509fe31550

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
